#!/bin/bash
#
# This starts and stops synchronator
#
### BEGIN INIT INFO
# Provides:          synchronator
# Required-Start:    $syslog $remote_fs
# Required-Stop:     $syslog $remote_fs
# Short-Description: synchronator
# Description:       synchronator
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO


# Source function library.
. /lib/lsb/init-functions

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NAME=synchronator
DAEMON=/usr/local/bin/$NAME
PIDLOCATION=/var/run/$NAME
PIDFILE=$PIDLOCATION/$NAME.pid
DAEMON_ARGS="-i /usr/local/etc/"$NAME".conf -d"
USER=root

[ -x $DAEMON ] || exit 0

[ -d $PIDLOCATION ] || mkdir $PIDLOCATION

chown $USER:$USER $PIDLOCATION

RETVAL=0

start() {
    echo -n "Starting synchronator: "
    start-stop-daemon --start --chuid $USER --quiet --pidfile "$PIDFILE" \
                      --exec "$DAEMON" -b --oknodo -- $DAEMON_ARGS
    log_end_msg $?
}

stop() {
    echo -n "Shutting down synchronator: "
    start-stop-daemon --stop --quiet --pidfile "$PIDFILE" \
                --retry 1 --oknodo
    log_end_msg $?
}

restart() {
    stop
    sleep 1
    start
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    status)
        status_of_proc -p $PIDFILE $DAEMON $NAME
    ;;
    restart)
        restart
    ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
    ;;
esac

exit 0


